[workspace]
members = ["server", "crypto", "crypto_java"]

[patch.crates-io]
noise-protocol = { path = "../noise-rust/noise-protocol" }
noise-rust-crypto = { path = "../noise-rust/noise-rust-crypto" }
