[workspace]
members = ["server", "crypto", "crypto_java", "web", "web_compiled"]

[patch.crates-io]
noise-protocol = { git = "https://github.com/exrook/noise-rust/" }
noise-rust-crypto = { git = "https://github.com/exrook/noise-rust/" }
