[package]
name = "Server"
version = "0.1.0"
authors = ["fruit <danieltapham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "1.4"
tiny_http = "0.7"
